dist: trusty
os: linux
language: java
jdk:
- oraclejdk8

env:
  global:

addons:
  ssh_known_hosts:
  - 47.244.152.125

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --remote
  - openssl aes-256-cbc -K $encrypted_1a174ea4ff88_key -iv $encrypted_1a174ea4ff88_iv -in id_rsa_light.enc -out id_rsa_light -d
  - chmod u=r,og-rwx id_rsa_light

install: mvn clean install -U -P pro -V -Dmaven.javadoc.skip=true -DskipTests=true

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/travis.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - light0x00@163.com
    on_success: change
    on_failure: always
