
server:
  port: 8082
  servlet:
    context-path: /blog-api
  multipart:
    enabled: true
  tomcat:
      uri-encoding: UTF-8

spring:
  mvc:
    favicon:
      enabled: true
  profiles:
    active: @env@
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


mybatis-plus:
  typeEnumsPackage: com.light.blog.dao.entity
  global-config:
      refresh: true
  #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  field-strategy: 0
  mapperLocations: classpath*:mapper/*.xml