# 热重启开关
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: blog
    password: ${MYSQL_BLOG_PWD}

app:
  url: blog.light0x00.com
  context-path: ${server.servlet.context-path}
  cookie:
    domain: light0x00.com
    path: /
    max-age: 1800
    token-key: token
  allow-origins:
    - https://blog.light0x00.com
    - http://blog.light0x00.com
  log:
    path: /home/user/app/blog-api/logs

